apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: java-app
data:
  DB_HOST: "mysql.java-app.svc.cluster.local"  # stable DNS from StatefulSet
  DB_PORT: "3306"
  DB_NAME: "testdb"
  DB_USER: "appuser"